version: '3'

services:
  vote:
    image: springsoft/voting-vote
    build:
      context: ./vote
      dockerfile: Dockerfile
  result:
    image: springsoft/voting-result
    build:
      context: ./result
      dockerfile: Dockerfile
  worker:
    image: springsoft/voting-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
